POST http://localhost:8080/rest/processes/org.n52.eopad.ndvi/jobs HTTP/1.1
Content-Type: application/json

{
   "inputs":[
      {
         "id": "INPUT_SOURCE",
         "input":{
            "format":{
               "mimeType": "text/plain"
            },
            "value": "S2A_MSIL2A_20190629T103031_N0212_R108_T32UNB_20190629T135351"
         }
      }
   ],
   "outputs":[
      {
         "id": "OUTPUT_RASTER",
         "format":{
            "mimeType": "text/plain"
         },
         "transmissionMode": "value"
      }
   ]
}